// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: UserRPC.proto
// Protobuf C++ Version: 5.29.2

#include "UserRPC.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace TestGRPC {
}  // namespace TestGRPC
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_UserRPC_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_UserRPC_2eproto = nullptr;
const ::uint32_t TableStruct_UserRPC_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_UserRPC_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rUserRPC.proto\022\010TestGRPC\032\nUser.proto2\374\001"
    "\n\013UserService\0226\n\007GetUser\022\031.TestGRPC.User"
    "AccountName\032\016.TestGRPC.User\"\000\0228\n\016GetUser"
    "sByRole\022\022.TestGRPC.UserRole\032\016.TestGRPC.U"
    "ser\"\0000\001\0226\n\010AddUsers\022\016.TestGRPC.User\032\026.Te"
    "stGRPC.CommonNumber\"\000(\001\022C\n\013DeleteUsers\022\031"
    ".TestGRPC.UserAccountName\032\023.TestGRPC.Com"
    "monMsg\"\000(\0010\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_UserRPC_2eproto_deps[1] =
    {
        &::descriptor_table_User_2eproto,
};
static ::absl::once_flag descriptor_table_UserRPC_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_UserRPC_2eproto = {
    false,
    false,
    300,
    descriptor_table_protodef_UserRPC_2eproto,
    "UserRPC.proto",
    &descriptor_table_UserRPC_2eproto_once,
    descriptor_table_UserRPC_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_UserRPC_2eproto::offsets,
    file_level_enum_descriptors_UserRPC_2eproto,
    file_level_service_descriptors_UserRPC_2eproto,
};
namespace TestGRPC {
// @@protoc_insertion_point(namespace_scope)
}  // namespace TestGRPC
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_UserRPC_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
