// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: User.proto
// Protobuf C++ Version: 5.29.2

#include "User.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace TestGRPC {

inline constexpr UserRole::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : role_{static_cast< ::TestGRPC::Role >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserRole::UserRole(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserRoleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserRoleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserRoleDefaultTypeInternal() {}
  union {
    UserRole _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserRoleDefaultTypeInternal _UserRole_default_instance_;

inline constexpr UserAccountName::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : accountname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserAccountName::UserAccountName(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserAccountNameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserAccountNameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserAccountNameDefaultTypeInternal() {}
  union {
    UserAccountName _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserAccountNameDefaultTypeInternal _UserAccountName_default_instance_;

inline constexpr User::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : accountname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        accountpwd_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        age_{0u},
        userrole_{static_cast< ::TestGRPC::Role >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR User::User(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserDefaultTypeInternal() {}
  union {
    User _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserDefaultTypeInternal _User_default_instance_;

inline constexpr CommonNumber::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : num_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CommonNumber::CommonNumber(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CommonNumberDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommonNumberDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommonNumberDefaultTypeInternal() {}
  union {
    CommonNumber _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommonNumberDefaultTypeInternal _CommonNumber_default_instance_;

inline constexpr CommonMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        issucess_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CommonMsg::CommonMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CommonMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommonMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommonMsgDefaultTypeInternal() {}
  union {
    CommonMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommonMsgDefaultTypeInternal _CommonMsg_default_instance_;
}  // namespace TestGRPC
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_User_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_User_2eproto = nullptr;
const ::uint32_t
    TableStruct_User_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TestGRPC::User, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TestGRPC::User, _impl_.accountname_),
        PROTOBUF_FIELD_OFFSET(::TestGRPC::User, _impl_.accountpwd_),
        PROTOBUF_FIELD_OFFSET(::TestGRPC::User, _impl_.nickname_),
        PROTOBUF_FIELD_OFFSET(::TestGRPC::User, _impl_.age_),
        PROTOBUF_FIELD_OFFSET(::TestGRPC::User, _impl_.userrole_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TestGRPC::UserRole, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TestGRPC::UserRole, _impl_.role_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TestGRPC::UserAccountName, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TestGRPC::UserAccountName, _impl_.accountname_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TestGRPC::CommonMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TestGRPC::CommonMsg, _impl_.issucess_),
        PROTOBUF_FIELD_OFFSET(::TestGRPC::CommonMsg, _impl_.msg_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TestGRPC::CommonNumber, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TestGRPC::CommonNumber, _impl_.num_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::TestGRPC::User)},
        {13, -1, -1, sizeof(::TestGRPC::UserRole)},
        {22, -1, -1, sizeof(::TestGRPC::UserAccountName)},
        {31, -1, -1, sizeof(::TestGRPC::CommonMsg)},
        {41, -1, -1, sizeof(::TestGRPC::CommonNumber)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::TestGRPC::_User_default_instance_._instance,
    &::TestGRPC::_UserRole_default_instance_._instance,
    &::TestGRPC::_UserAccountName_default_instance_._instance,
    &::TestGRPC::_CommonMsg_default_instance_._instance,
    &::TestGRPC::_CommonNumber_default_instance_._instance,
};
const char descriptor_table_protodef_User_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nUser.proto\022\010TestGRPC\"p\n\004User\022\023\n\013accoun"
    "tName\030\001 \001(\t\022\022\n\naccountPWD\030\002 \001(\t\022\020\n\010nickN"
    "ame\030\003 \001(\t\022\013\n\003age\030\004 \001(\r\022 \n\010userRole\030\005 \001(\016"
    "2\016.TestGRPC.Role\"(\n\010UserRole\022\034\n\004role\030\001 \001"
    "(\0162\016.TestGRPC.Role\"&\n\017UserAccountName\022\023\n"
    "\013accountName\030\001 \001(\t\"*\n\tCommonMsg\022\020\n\010isSuc"
    "ess\030\001 \001(\010\022\013\n\003msg\030\002 \001(\t\"\033\n\014CommonNumber\022\013"
    "\n\003num\030\001 \001(\r*\033\n\004Role\022\010\n\004USER\020\000\022\t\n\005ADMIN\020\001"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_User_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_User_2eproto = {
    false,
    false,
    328,
    descriptor_table_protodef_User_2eproto,
    "User.proto",
    &descriptor_table_User_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_User_2eproto::offsets,
    file_level_enum_descriptors_User_2eproto,
    file_level_service_descriptors_User_2eproto,
};
namespace TestGRPC {
const ::google::protobuf::EnumDescriptor* Role_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_User_2eproto);
  return file_level_enum_descriptors_User_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Role_internal_data_[] = {
    131072u, 0u, };
bool Role_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class User::_Internal {
 public:
};

User::User(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TestGRPC.User)
}
inline PROTOBUF_NDEBUG_INLINE User::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::TestGRPC::User& from_msg)
      : accountname_(arena, from.accountname_),
        accountpwd_(arena, from.accountpwd_),
        nickname_(arena, from.nickname_),
        _cached_size_{0} {}

User::User(
    ::google::protobuf::Arena* arena,
    const User& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  User* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, age_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, age_),
           offsetof(Impl_, userrole_) -
               offsetof(Impl_, age_) +
               sizeof(Impl_::userrole_));

  // @@protoc_insertion_point(copy_constructor:TestGRPC.User)
}
inline PROTOBUF_NDEBUG_INLINE User::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : accountname_(arena),
        accountpwd_(arena),
        nickname_(arena),
        _cached_size_{0} {}

inline void User::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, age_),
           0,
           offsetof(Impl_, userrole_) -
               offsetof(Impl_, age_) +
               sizeof(Impl_::userrole_));
}
User::~User() {
  // @@protoc_insertion_point(destructor:TestGRPC.User)
  SharedDtor(*this);
}
inline void User::SharedDtor(MessageLite& self) {
  User& this_ = static_cast<User&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.accountname_.Destroy();
  this_._impl_.accountpwd_.Destroy();
  this_._impl_.nickname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* User::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) User(arena);
}
constexpr auto User::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(User),
                                            alignof(User));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull User::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_User_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &User::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<User>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &User::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<User>(), &User::ByteSizeLong,
            &User::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(User, _impl_._cached_size_),
        false,
    },
    &User::kDescriptorMethods,
    &descriptor_table_User_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* User::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 51, 2> User::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TestGRPC::User>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string accountName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(User, _impl_.accountname_)}},
    // string accountPWD = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(User, _impl_.accountpwd_)}},
    // string nickName = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(User, _impl_.nickname_)}},
    // uint32 age = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(User, _impl_.age_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(User, _impl_.age_)}},
    // .TestGRPC.Role userRole = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(User, _impl_.userrole_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(User, _impl_.userrole_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string accountName = 1;
    {PROTOBUF_FIELD_OFFSET(User, _impl_.accountname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string accountPWD = 2;
    {PROTOBUF_FIELD_OFFSET(User, _impl_.accountpwd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string nickName = 3;
    {PROTOBUF_FIELD_OFFSET(User, _impl_.nickname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 age = 4;
    {PROTOBUF_FIELD_OFFSET(User, _impl_.age_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .TestGRPC.Role userRole = 5;
    {PROTOBUF_FIELD_OFFSET(User, _impl_.userrole_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\15\13\12\10\0\0\0\0"
    "TestGRPC.User"
    "accountName"
    "accountPWD"
    "nickName"
  }},
};

PROTOBUF_NOINLINE void User::Clear() {
// @@protoc_insertion_point(message_clear_start:TestGRPC.User)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.accountname_.ClearToEmpty();
  _impl_.accountpwd_.ClearToEmpty();
  _impl_.nickname_.ClearToEmpty();
  ::memset(&_impl_.age_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.userrole_) -
      reinterpret_cast<char*>(&_impl_.age_)) + sizeof(_impl_.userrole_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* User::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const User& this_ = static_cast<const User&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* User::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const User& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:TestGRPC.User)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string accountName = 1;
          if (!this_._internal_accountname().empty()) {
            const std::string& _s = this_._internal_accountname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TestGRPC.User.accountName");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string accountPWD = 2;
          if (!this_._internal_accountpwd().empty()) {
            const std::string& _s = this_._internal_accountpwd();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TestGRPC.User.accountPWD");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string nickName = 3;
          if (!this_._internal_nickname().empty()) {
            const std::string& _s = this_._internal_nickname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TestGRPC.User.nickName");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // uint32 age = 4;
          if (this_._internal_age() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_age(), target);
          }

          // .TestGRPC.Role userRole = 5;
          if (this_._internal_userrole() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                5, this_._internal_userrole(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:TestGRPC.User)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t User::ByteSizeLong(const MessageLite& base) {
          const User& this_ = static_cast<const User&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t User::ByteSizeLong() const {
          const User& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:TestGRPC.User)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string accountName = 1;
            if (!this_._internal_accountname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_accountname());
            }
            // string accountPWD = 2;
            if (!this_._internal_accountpwd().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_accountpwd());
            }
            // string nickName = 3;
            if (!this_._internal_nickname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_nickname());
            }
            // uint32 age = 4;
            if (this_._internal_age() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_age());
            }
            // .TestGRPC.Role userRole = 5;
            if (this_._internal_userrole() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_userrole());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void User::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<User*>(&to_msg);
  auto& from = static_cast<const User&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestGRPC.User)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_accountname().empty()) {
    _this->_internal_set_accountname(from._internal_accountname());
  }
  if (!from._internal_accountpwd().empty()) {
    _this->_internal_set_accountpwd(from._internal_accountpwd());
  }
  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (from._internal_age() != 0) {
    _this->_impl_.age_ = from._impl_.age_;
  }
  if (from._internal_userrole() != 0) {
    _this->_impl_.userrole_ = from._impl_.userrole_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void User::CopyFrom(const User& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestGRPC.User)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void User::InternalSwap(User* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accountname_, &other->_impl_.accountname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accountpwd_, &other->_impl_.accountpwd_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(User, _impl_.userrole_)
      + sizeof(User::_impl_.userrole_)
      - PROTOBUF_FIELD_OFFSET(User, _impl_.age_)>(
          reinterpret_cast<char*>(&_impl_.age_),
          reinterpret_cast<char*>(&other->_impl_.age_));
}

::google::protobuf::Metadata User::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserRole::_Internal {
 public:
};

UserRole::UserRole(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TestGRPC.UserRole)
}
UserRole::UserRole(
    ::google::protobuf::Arena* arena, const UserRole& from)
    : UserRole(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE UserRole::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void UserRole::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.role_ = {};
}
UserRole::~UserRole() {
  // @@protoc_insertion_point(destructor:TestGRPC.UserRole)
  SharedDtor(*this);
}
inline void UserRole::SharedDtor(MessageLite& self) {
  UserRole& this_ = static_cast<UserRole&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* UserRole::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserRole(arena);
}
constexpr auto UserRole::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UserRole),
                                            alignof(UserRole));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserRole::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserRole_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserRole::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserRole>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserRole::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserRole>(), &UserRole::ByteSizeLong,
            &UserRole::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserRole, _impl_._cached_size_),
        false,
    },
    &UserRole::kDescriptorMethods,
    &descriptor_table_User_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserRole::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> UserRole::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TestGRPC::UserRole>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .TestGRPC.Role role = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserRole, _impl_.role_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UserRole, _impl_.role_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .TestGRPC.Role role = 1;
    {PROTOBUF_FIELD_OFFSET(UserRole, _impl_.role_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void UserRole::Clear() {
// @@protoc_insertion_point(message_clear_start:TestGRPC.UserRole)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.role_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserRole::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserRole& this_ = static_cast<const UserRole&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserRole::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserRole& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:TestGRPC.UserRole)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .TestGRPC.Role role = 1;
          if (this_._internal_role() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_role(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:TestGRPC.UserRole)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserRole::ByteSizeLong(const MessageLite& base) {
          const UserRole& this_ = static_cast<const UserRole&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserRole::ByteSizeLong() const {
          const UserRole& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:TestGRPC.UserRole)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .TestGRPC.Role role = 1;
            if (this_._internal_role() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_role());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserRole::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserRole*>(&to_msg);
  auto& from = static_cast<const UserRole&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestGRPC.UserRole)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_role() != 0) {
    _this->_impl_.role_ = from._impl_.role_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserRole::CopyFrom(const UserRole& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestGRPC.UserRole)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserRole::InternalSwap(UserRole* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.role_, other->_impl_.role_);
}

::google::protobuf::Metadata UserRole::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserAccountName::_Internal {
 public:
};

UserAccountName::UserAccountName(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TestGRPC.UserAccountName)
}
inline PROTOBUF_NDEBUG_INLINE UserAccountName::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::TestGRPC::UserAccountName& from_msg)
      : accountname_(arena, from.accountname_),
        _cached_size_{0} {}

UserAccountName::UserAccountName(
    ::google::protobuf::Arena* arena,
    const UserAccountName& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserAccountName* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:TestGRPC.UserAccountName)
}
inline PROTOBUF_NDEBUG_INLINE UserAccountName::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : accountname_(arena),
        _cached_size_{0} {}

inline void UserAccountName::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserAccountName::~UserAccountName() {
  // @@protoc_insertion_point(destructor:TestGRPC.UserAccountName)
  SharedDtor(*this);
}
inline void UserAccountName::SharedDtor(MessageLite& self) {
  UserAccountName& this_ = static_cast<UserAccountName&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.accountname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UserAccountName::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserAccountName(arena);
}
constexpr auto UserAccountName::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserAccountName),
                                            alignof(UserAccountName));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserAccountName::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserAccountName_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserAccountName::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserAccountName>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserAccountName::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserAccountName>(), &UserAccountName::ByteSizeLong,
            &UserAccountName::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserAccountName, _impl_._cached_size_),
        false,
    },
    &UserAccountName::kDescriptorMethods,
    &descriptor_table_User_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserAccountName::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 44, 2> UserAccountName::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TestGRPC::UserAccountName>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string accountName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserAccountName, _impl_.accountname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string accountName = 1;
    {PROTOBUF_FIELD_OFFSET(UserAccountName, _impl_.accountname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\13\0\0\0\0\0\0"
    "TestGRPC.UserAccountName"
    "accountName"
  }},
};

PROTOBUF_NOINLINE void UserAccountName::Clear() {
// @@protoc_insertion_point(message_clear_start:TestGRPC.UserAccountName)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.accountname_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserAccountName::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserAccountName& this_ = static_cast<const UserAccountName&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserAccountName::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserAccountName& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:TestGRPC.UserAccountName)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string accountName = 1;
          if (!this_._internal_accountname().empty()) {
            const std::string& _s = this_._internal_accountname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TestGRPC.UserAccountName.accountName");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:TestGRPC.UserAccountName)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserAccountName::ByteSizeLong(const MessageLite& base) {
          const UserAccountName& this_ = static_cast<const UserAccountName&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserAccountName::ByteSizeLong() const {
          const UserAccountName& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:TestGRPC.UserAccountName)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string accountName = 1;
            if (!this_._internal_accountname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_accountname());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserAccountName::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserAccountName*>(&to_msg);
  auto& from = static_cast<const UserAccountName&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestGRPC.UserAccountName)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_accountname().empty()) {
    _this->_internal_set_accountname(from._internal_accountname());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserAccountName::CopyFrom(const UserAccountName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestGRPC.UserAccountName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserAccountName::InternalSwap(UserAccountName* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accountname_, &other->_impl_.accountname_, arena);
}

::google::protobuf::Metadata UserAccountName::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CommonMsg::_Internal {
 public:
};

CommonMsg::CommonMsg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TestGRPC.CommonMsg)
}
inline PROTOBUF_NDEBUG_INLINE CommonMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::TestGRPC::CommonMsg& from_msg)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

CommonMsg::CommonMsg(
    ::google::protobuf::Arena* arena,
    const CommonMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CommonMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.issucess_ = from._impl_.issucess_;

  // @@protoc_insertion_point(copy_constructor:TestGRPC.CommonMsg)
}
inline PROTOBUF_NDEBUG_INLINE CommonMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void CommonMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.issucess_ = {};
}
CommonMsg::~CommonMsg() {
  // @@protoc_insertion_point(destructor:TestGRPC.CommonMsg)
  SharedDtor(*this);
}
inline void CommonMsg::SharedDtor(MessageLite& self) {
  CommonMsg& this_ = static_cast<CommonMsg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CommonMsg::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CommonMsg(arena);
}
constexpr auto CommonMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CommonMsg),
                                            alignof(CommonMsg));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CommonMsg::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CommonMsg_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CommonMsg::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CommonMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CommonMsg::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CommonMsg>(), &CommonMsg::ByteSizeLong,
            &CommonMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CommonMsg, _impl_._cached_size_),
        false,
    },
    &CommonMsg::kDescriptorMethods,
    &descriptor_table_User_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CommonMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2> CommonMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TestGRPC::CommonMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CommonMsg, _impl_.msg_)}},
    // bool isSucess = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CommonMsg, _impl_.issucess_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommonMsg, _impl_.issucess_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool isSucess = 1;
    {PROTOBUF_FIELD_OFFSET(CommonMsg, _impl_.issucess_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(CommonMsg, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\3\0\0\0\0\0"
    "TestGRPC.CommonMsg"
    "msg"
  }},
};

PROTOBUF_NOINLINE void CommonMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:TestGRPC.CommonMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.issucess_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CommonMsg::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CommonMsg& this_ = static_cast<const CommonMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CommonMsg::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CommonMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:TestGRPC.CommonMsg)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool isSucess = 1;
          if (this_._internal_issucess() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_issucess(), target);
          }

          // string msg = 2;
          if (!this_._internal_msg().empty()) {
            const std::string& _s = this_._internal_msg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TestGRPC.CommonMsg.msg");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:TestGRPC.CommonMsg)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CommonMsg::ByteSizeLong(const MessageLite& base) {
          const CommonMsg& this_ = static_cast<const CommonMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CommonMsg::ByteSizeLong() const {
          const CommonMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:TestGRPC.CommonMsg)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string msg = 2;
            if (!this_._internal_msg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msg());
            }
            // bool isSucess = 1;
            if (this_._internal_issucess() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CommonMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CommonMsg*>(&to_msg);
  auto& from = static_cast<const CommonMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestGRPC.CommonMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_issucess() != 0) {
    _this->_impl_.issucess_ = from._impl_.issucess_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommonMsg::CopyFrom(const CommonMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestGRPC.CommonMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CommonMsg::InternalSwap(CommonMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
        swap(_impl_.issucess_, other->_impl_.issucess_);
}

::google::protobuf::Metadata CommonMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CommonNumber::_Internal {
 public:
};

CommonNumber::CommonNumber(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TestGRPC.CommonNumber)
}
CommonNumber::CommonNumber(
    ::google::protobuf::Arena* arena, const CommonNumber& from)
    : CommonNumber(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CommonNumber::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CommonNumber::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.num_ = {};
}
CommonNumber::~CommonNumber() {
  // @@protoc_insertion_point(destructor:TestGRPC.CommonNumber)
  SharedDtor(*this);
}
inline void CommonNumber::SharedDtor(MessageLite& self) {
  CommonNumber& this_ = static_cast<CommonNumber&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* CommonNumber::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CommonNumber(arena);
}
constexpr auto CommonNumber::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CommonNumber),
                                            alignof(CommonNumber));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CommonNumber::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CommonNumber_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CommonNumber::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CommonNumber>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CommonNumber::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CommonNumber>(), &CommonNumber::ByteSizeLong,
            &CommonNumber::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CommonNumber, _impl_._cached_size_),
        false,
    },
    &CommonNumber::kDescriptorMethods,
    &descriptor_table_User_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CommonNumber::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CommonNumber::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TestGRPC::CommonNumber>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 num = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CommonNumber, _impl_.num_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommonNumber, _impl_.num_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 num = 1;
    {PROTOBUF_FIELD_OFFSET(CommonNumber, _impl_.num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CommonNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:TestGRPC.CommonNumber)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.num_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CommonNumber::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CommonNumber& this_ = static_cast<const CommonNumber&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CommonNumber::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CommonNumber& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:TestGRPC.CommonNumber)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 num = 1;
          if (this_._internal_num() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_num(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:TestGRPC.CommonNumber)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CommonNumber::ByteSizeLong(const MessageLite& base) {
          const CommonNumber& this_ = static_cast<const CommonNumber&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CommonNumber::ByteSizeLong() const {
          const CommonNumber& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:TestGRPC.CommonNumber)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint32 num = 1;
            if (this_._internal_num() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_num());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CommonNumber::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CommonNumber*>(&to_msg);
  auto& from = static_cast<const CommonNumber&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestGRPC.CommonNumber)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_num() != 0) {
    _this->_impl_.num_ = from._impl_.num_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommonNumber::CopyFrom(const CommonNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestGRPC.CommonNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CommonNumber::InternalSwap(CommonNumber* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.num_, other->_impl_.num_);
}

::google::protobuf::Metadata CommonNumber::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace TestGRPC
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_User_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
